### ISSUE TITLE
Do the shadows

### ISSUE THREAD

**Issue by Neo-Oli** [RolandR/bahnhofsuhr#1]
This needs to have shadows similar to the one on http://moserbaer.ch

**Comment by Neo-Oli** [comment]
Is there any progress on this?

**Comment by Neo-Oli** [comment]
Closing this, because https://github.com/RolandR/bahnhofsuhr/commit/bb546dcb2ebc1a8aa0855cc14bdba1388439fe3f seems to have fixed this

**Comment by RolandR** [comment]
Ah. Right.
